TARFILES = Makefile scannerAlt.mll parserAlt.mly astAlt.mli hello_world.ml

OBJS = parserAlt.cmo scannerAlt.cmo hello_world.cmo

hello_world : $(OBJS)
	ocamlc -o hello_world $(OBJS)

scannerAlt.ml : scannerAlt.mll
	ocamllex scannerAlt.mll

parserAlt.ml parserAlt.mli : parserAlt.mly
	ocamlyacc parserAlt.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

calculator.tar.gz : $(TARFILES)
	cd .. && tar zcf calculator/calculator.tar.gz $(TARFILES:%=calculator/%)

.PHONY : clean
clean :
	rm -f hello_world parserAlt.ml parserAlt.mli scannerAlt.ml *.cmo *.cmi

# Generated by ocamldep *.ml *.mli
hello_world.cmo: scannerAlt.cmo parserAlt.cmi astAlt.cmi 
hello_world.cmx: scannerAlt.cmx parserAlt.cmx astAlt.cmi 
parserAlt.cmo: astAlt.cmi parserAlt.cmi 
parserAlt.cmx: astAlt.cmi parserAlt.cmi 
scannerAlt.cmo: parserAlt.cmi 
scannerAlt.cmx: parserAlt.cmx 
parserAlt.cmi: astAlt.cmi 
